package com.example.webshop.model;



import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.vaadin.annotations.AutoGenerated;

@Entity
public class User implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1716065610263851329L;
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	private String surname;
	private String name;
	private String username;
	private String password;
	private Date birthday;
	private String street;
	private String housenumber;
	private String postcode;
	private String city;
	
	public User() {
		// TODO Auto-generated constructor stub
	}

	
	/**
	 * @param surname
	 * @param name
	 * @param password
	 * @param birthday
	 * @param street
	 * @param housenumber
	 * @param postcode
	 * @param city
	 */
	public User(String surname, String name, String password, Date birthday, String street,
			String housenumber, String postcode, String city) {
		super();
		this.surname = surname;
		this.password = password;
		this.username = surname + "." + name;
		this.name = name;
		this.birthday = birthday;
		this.street = street;
		this.housenumber = housenumber;
		this.postcode = postcode;
		this.city = city;
	}


	public long getId() {
		return id;
	}

	
	public void setId(long id) {
		this.id = id;
	}

	
	public String getSurname() {
		return surname;
	}

	
	public void setSurname(String surname) {
		this.surname = surname;
	}

	
	public String getName() {
		return name;
	}

	
	public void setName(String name) {
		this.name = name;
	}

	
	public Date getBirthday() {
		return birthday;
	}

	
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	
	public String getStreet() {
		return street;
	}

	
	public void setStreet(String street) {
		this.street = street;
	}

	
	public String getHousenumber() {
		return housenumber;
	}

	
	public void setHousenumber(String housenumber) {
		this.housenumber = housenumber;
	}

	
	public String getPostcode() {
		return postcode;
	}

	
	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	
	public String getCity() {
		return city;
	}

	
	public void setCity(String city) {
		this.city = city;
	}
	
	
	
	public String getPassword() {
		return password;
	}


	
	public void setPassword(String password) {
		this.password = password;
	}


	
	public String getUsername() {
		return username;
	}


	
	public void setUsername(String username) {
		this.username = username;
	}


	public boolean isUser() {
		return true;
	}
	

}
